#! /bin/sh
### BEGIN INIT INFO
# Provides:          cstbox-serialnmea
# Required-Start:    $remote_fs $syslog cstbox-dbus cstbox-evtmgr
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox serial NMEA devices support service
# Description:       This package adds to an existing CSTBox framework the support
#                    for serial NMEA products.
#                    It includes the models of currently support products.
### END INIT INFO

# Author: Eric Pascual <eric.pascual@cstb.fr>

DESC="CSTBox Serial NMEA HAL"
INIT_SEQ=94
NAME=cstbox-serialnmea
DAEMON=/opt/cstbox/bin/serial-nmead.py
DAEMON_ARGS=
INIT_VERBOSE=yes

. /opt/cstbox/lib/init/init-functions

